export const mockPosts = [
  {
    name: 'Super Oligei',
    date: (new Date()).toLocaleDateString(),
    description: 'best tutor ever',
    school: 'UBC',
    course: 'CPSC 455',
    price: '$5',
  },
  {
    name: 'Super Oligei',
    date: (new Date()).toLocaleDateString(),
    description: 'best tutor ever',
    school: 'UBC',
    course: 'CPSC 455',
    price: '$5',
  },
  {
    name: 'Super Oligei',
    date: (new Date()).toLocaleDateString(),
    description: 'best tutor ever',
    school: 'UBC',
    course: 'CPSC 455',
    price: '$5',
  },
  {
    name: 'Super Oligei',
    date: (new Date()).toLocaleDateString(),
    description: 'best tutor ever',
    school: 'UBC',
    course: 'CPSC 455',
    price: '$5',
  },
  {
    name: 'Super Oligei',
    date: (new Date()).toLocaleDateString(),
    description: 'best tutor ever',
    school: 'UBC',
    course: 'CPSC 455',
    price: '$5',
  },
];
